### ISSUE TITLE
assigned bug.

### ISSUE THREAD

**Issue by infinityfroze98** [softlong/LiftProf_Native#3]
[IMG_7405.zip](https://github.com/softlong/LiftProf_Native/files/2651586/IMG_7405.zip)
[IMG_7407.zip](https://github.com/softlong/LiftProf_Native/files/2651587/IMG_7407.zip)

**Comment by infinityfroze98** [comment]
there is a bug when i clicked 7th & 8th Dec,it doesnt show the task that i had created earlier,unless i quit and the app and launch again,and it will appears on any today's date

**Comment by TianFengRL** [comment]
这个bug已经由服务器修复
